
[package]
name = "easy_linked_list"
version = "0.1.1"
authors = ["Saeed Safi <safi.saeed1999@gamil.com>"]
edition = "2021"
description = "linked list is easy to work"
license = "MIT"

[dependencies]
